FROM splunk/universalforwarder:latest

ARG BUILD_DATE
ARG VCS_REF

# Good docker practice, plus we get microbadger badges
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-url="https://github.com/funkypenguin/grin-pool.git" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.schema-version="2.2-r1"
      
USER root

ENV SPLUNK_START_ARGS=--accept-license

EXPOSE 9997

COPY run.sh /

ENTRYPOINT ["/run.sh"]
